### ISSUE TITLE
Issue Validação de "ano" em Book

### ISSUE THREAD

**Issue by brunol-pereira** [brunol-pereira/DC-UFSCar-ES2-202201-Grupo-NomeDoGrupo#1]
Na funcionalidade **Inserção de item bibliográfico** (_BibTeX_ → _New entry_), para a categoria Book, o campo Year deve ser um ano válido de acordo com o calendário da linguagem Java.

**Comment by Vitorrecoaro** [comment]
Issue resolvida na Issue 2 "Validação de ano em article"
